name: flutter_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:  
  firebase_core:  ^2.0.0 
  firebase_remote_config: ^3.0.1
  firebase_analytics: ^10.0.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  google_mobile_ads: ^3.0.0
  package_info_plus: ^4.0.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
